### ISSUE TITLE
How to disable tkinter modules

### ISSUE THREAD

**Issue by ChaeYeon01** [scientisst/BioSPPy#48]
Hi.
I have a problem :
https://github.com/chaquo/chaquopy/issues/1145

I need to use chaquopy(Python SDK for Android) and import pyhrv in my android studio project. But 'import pyhrv' gets 'no module tkinter error'.
![pyhrv_cv2](https://github.com/scientisst/BioSPPy/assets/91841696/f0ddb3be-3509-4b52-b02c-4b3d01b89bf0)
The error was also caused at biosppy module.

Chaquopy doesn't support tkinter. but I don't use tkinter. 

I think biosppy might be related to tkinter.
I don't want tkinter to be used.
Is there any way to tolerate the situation where tkinter is unavailable?

thanks.

**Comment by sofia3ms** [comment]
Hello @ChaeYeon01 !! Thank you for reporting this. I think this error is happening because the inter_plotting submodule, which uses tkinter, is being loaded in the signals.ecg and signals.acc files. To fix this and avoid future issues, we changed it so that biosppy doesn't import this submodule unless it is explicitly called. Can you check if it works for you now?

**Comment by ChaeYeon01** [comment]
Thank you for your comment.
But it still doesn't work...
I keep getting the same error.

![image](https://github.com/scientisst/BioSPPy/assets/91841696/1f305631-745a-4201-8aed-3b2bc21071d0)

**Comment by ChaeYeon01** [comment]
Thank you for your comment!!
It works!!!
^오^

**Comment by sofia3ms** [comment]
Great!! 😊
